[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayFunctionLikeReturnTypeHints = false
includeInlayFunctionParameterTypeHints = false
includeInlayPropertyDeclarationTypeHints = false
includeInlayVariableTypeHints = false
